export const CACHE_KEY = {
  TOKEN: "SYSTEMSETTINGTOKEN", // 授权token
  LANGUAGE: "LANGUAGE", // 语言
  MT_RELOAD_TIME: "MT_RELOAD_TIME", // 刷新次数
  __MT__USER__: "__MT__USER__", // 用户信息
  MENU_FOCUS_UPDATE: "MENU_FOCUS_UPDATE", //
  __MT__PARENT_MENULIST_CACHE__: "__MT__PARENT_MENULIST_CACHE__",
  __MT__LOWER_MENULIST_CACHE__: "__MT__LOWER_MENULIST_CACHE__",
  __MT__CURRENT_SYSTEM: "__MT__CURRENT_SYSTEM",
};
