// 站点
export const SITE_ID = {
  ALL: 0, // 全部
  GUANG_ZHOU_NAN_ZHAN: "00321", // 广州南站
  GUANG_ZHOU_NAN_ZHAN_2: "00322", // 广州南站2
  GUANG_ZHOU_NAN_ZHAN_3: "00323", // 广州南站3
};

export const SITE_TEXT = {
  [SITE_ID.ALL]: "全部",
  [SITE_ID.GUANG_ZHOU_NAN_ZHAN]: "广州南站",
  [SITE_ID.GUANG_ZHOU_NAN_ZHAN_2]: "广州南站2",
  [SITE_ID.GUANG_ZHOU_NAN_ZHAN_3]: "广州南站3",
};

// 站点 options
export const SITE_OPTIONS = () => [
  {
    label: SITE_TEXT[SITE_ID.ALL],
    value: SITE_ID.ALL,
  },
  {
    label: SITE_TEXT[SITE_ID.GUANG_ZHOU_NAN_ZHAN],
    value: SITE_ID.GUANG_ZHOU_NAN_ZHAN,
  },
  {
    label: SITE_TEXT[SITE_ID.GUANG_ZHOU_NAN_ZHAN_2],
    value: SITE_ID.GUANG_ZHOU_NAN_ZHAN_2,
  },
  {
    label: SITE_TEXT[SITE_ID.GUANG_ZHOU_NAN_ZHAN_3],
    value: SITE_ID.GUANG_ZHOU_NAN_ZHAN_3,
  },
];

// 订单出票类型
export const TICKETS_TYPE = {
  ALL: 0, // 全部
  THERE_TICKETS: 1, // 有票
  NO_TICKET: 2, // 无票
  TIME_OUT: 3, // 超时
};

export const TICKETS_TYPE_TEXT = {
  [TICKETS_TYPE.ALL]: "全部",
  [TICKETS_TYPE.THERE_TICKETS]: "有票",
  [TICKETS_TYPE.NO_TICKET]: "无票",
  [TICKETS_TYPE.TIME_OUT]: "超时",
};

// 订单出票类型 options
export const TICKETS_TYPE_OPTIONS = () => [
  {
    label: TICKETS_TYPE_TEXT[TICKETS_TYPE.ALL],
    value: TICKETS_TYPE.ALL,
  },
  {
    label: TICKETS_TYPE_TEXT[TICKETS_TYPE.THERE_TICKETS],
    value: TICKETS_TYPE.THERE_TICKETS,
  },
  {
    label: TICKETS_TYPE_TEXT[TICKETS_TYPE.NO_TICKET],
    value: TICKETS_TYPE.NO_TICKET,
  },
  {
    label: TICKETS_TYPE_TEXT[TICKETS_TYPE.TIME_OUT],
    value: TICKETS_TYPE.TIME_OUT,
  },
];

// 车票状态
export const TICKETS_STATE = {
  SUCCESS: 1, // 成功
  FAIL: 2, // 失败
};

export const TICKETS_STATE_TEXT = {
  [TICKETS_STATE.SUCCESS]: "成功",
  [TICKETS_STATE.FAIL]: "失败",
};

export const TICKETS_STATE_OPTIONS = () => [
  {
    label: TICKETS_STATE_TEXT[TICKETS_STATE.SUCCESS],
    value: TICKETS_STATE.SUCCESS,
  },
  {
    label: TICKETS_STATE_TEXT[TICKETS_STATE.FAIL],
    value: TICKETS_STATE.FAIL,
  },
];

// 退票处理类型
export const REFUND_ACTION_TYPE = {
  SUCCESS: 1, // 退票成功
  FAIL: 2, // 退票失败
  REFUNDED: 3, // 退票退回
};

export const REFUND_ACTION_TYPE_TEXT = {
  [REFUND_ACTION_TYPE.SUCCESS]: "退票成功",
  [REFUND_ACTION_TYPE.FAIL]: "退票失败",
  [REFUND_ACTION_TYPE.REFUNDED]: "退票退回",
};

export const REFUND_ACTION_TYPE_OPTIONS = () => [
  {
    label: REFUND_ACTION_TYPE_TEXT[REFUND_ACTION_TYPE.SUCCESS],
    value: REFUND_ACTION_TYPE.SUCCESS,
  },
  {
    label: REFUND_ACTION_TYPE_TEXT[REFUND_ACTION_TYPE.FAIL],
    value: REFUND_ACTION_TYPE.FAIL,
  },
  {
    label: REFUND_ACTION_TYPE_TEXT[REFUND_ACTION_TYPE.REFUNDED],
    value: REFUND_ACTION_TYPE.REFUNDED,
  },
];

// 退票类型
export const REFUND_TYPE = {
  // READY_MONEY: 1, // 现金
  // READY_MONEY_SPECIAL: 2, // 现金特殊
  NON_READY_MONEY: 1, // 非现金
  // NON_READY_MONEY_SPECIAL: 4, // 非现金特殊
};

export const REFUND_TYPE_TEXT = {
  // [REFUND_TYPE.READY_MONEY]: "现金",
  // [REFUND_TYPE.READY_MONEY_SPECIAL]: "现金特殊",
  [REFUND_TYPE.NON_READY_MONEY]: "非现金",
  // [REFUND_TYPE.NON_READY_MONEY_SPECIAL]: "非现金特殊",
};

export const REFUND_TYPE_OPTIONS = () => [
  // {
  //   label: REFUND_TYPE_TEXT[REFUND_TYPE.READY_MONEY],
  //   value: REFUND_TYPE.READY_MONEY,
  // },
  // {
  //   label: REFUND_TYPE_TEXT[REFUND_TYPE.READY_MONEY_SPECIAL],
  //   value: REFUND_TYPE.READY_MONEY_SPECIAL,
  // },
  {
    label: REFUND_TYPE_TEXT[REFUND_TYPE.NON_READY_MONEY],
    value: REFUND_TYPE.NON_READY_MONEY,
  },
  // {
  //   label: REFUND_TYPE_TEXT[REFUND_TYPE.NON_READY_MONEY_SPECIAL],
  //   value: REFUND_TYPE.NON_READY_MONEY_SPECIAL,
  // },
];

// 退票费类型
export const REFUND_FEE_TYPE = {
  ALL: 0, // 全部
  SUCCESS: 1, // 出票
  REBOOK: 2, // 改签
};

export const REFUND_FEE_TYPE_TYPE = {
  [REFUND_FEE_TYPE.ALL]: "全部",
  [REFUND_FEE_TYPE.SUCCESS]: "出票",
  [REFUND_FEE_TYPE.REBOOK]: "改签",
};

export const REFUND_FEE_TYPE_OPTIONS = () => [
  {
    label: REFUND_FEE_TYPE_TYPE[REFUND_FEE_TYPE.ALL],
    value: REFUND_FEE_TYPE.ALL,
  },
  {
    label: REFUND_FEE_TYPE_TYPE[REFUND_FEE_TYPE.SUCCESS],
    value: REFUND_FEE_TYPE.SUCCESS,
  },
  {
    label: REFUND_FEE_TYPE_TYPE[REFUND_FEE_TYPE.REBOOK],
    value: REFUND_FEE_TYPE.REBOOK,
  },
];

// 会话状态
export const SESSION_STATE = {
  ALL: 0, // 全部
  WAIT_HANDLE: 1, //待处理
  HAS_SENT: 2, // 已处理
  HANDLE_SUCCESS: 3, // 处理成功
};

export const SESSION_STATE_TEXT = {
  [SESSION_STATE.ALL]: "全部",
  [SESSION_STATE.WAIT_HANDLE]: "待处理",
  [SESSION_STATE.HAS_SENT]: "已处理",
  [SESSION_STATE.HANDLE_SUCCESS]: "处理成功",
};

export const SESSION_STATE_OPTIONS = () => [
  {
    label: SESSION_STATE_TEXT[SESSION_STATE.ALL],
    value: SESSION_STATE.ALL,
  },
  {
    label: SESSION_STATE_TEXT[SESSION_STATE.WAIT_HANDLE],
    value: SESSION_STATE.WAIT_HANDLE,
  },
  {
    label: SESSION_STATE_TEXT[SESSION_STATE.HAS_SENT],
    value: SESSION_STATE.HAS_SENT,
  },
  {
    label: SESSION_STATE_TEXT[SESSION_STATE.HANDLE_SUCCESS],
    value: SESSION_STATE.HANDLE_SUCCESS,
  },
];

// 订单标记
export const ORDER_FLAG = {
  GENERAL_ORDER: 0, // 一般订单
  BUCKLE_ORDER: 2, // 扣位订单
};

export const ORDER_FLAG_TEXT = {
  [ORDER_FLAG.GENERAL_ORDER]: "一般订单",
  [ORDER_FLAG.BUCKLE_ORDER]: "扣位订单",
};

// 订单出票类型
export const ORDER_TICKET_TYPE = {
  ONE_WAY_TICKETS: 0, // 单程票
  CONNECTING_TICKET: 1, // 联程票
};

// 行程类型
export const TICKET_TYPE = {
  FIRST_RIDE: 1, // 第一程
  SECOND_TRIP: 2, // 第二程
};

export const TICKET_TYPE_TEXT = {
  [TICKET_TYPE.FIRST_RIDE]: "单程",
  [TICKET_TYPE.SECOND_TRIP]: "联程",
};

// 证件类型
export const PASSPORT_TYPE = {
  IDENTITY_CARD: 1, // 身份证
  PASSPORT: 2, // 护照
  HONG_KONG_AND_MACAO_MAINLAND_PASS: 7, // 回乡证(港澳居民来往内地通行证)
  TAIWAN_COMPATRIOT_CERTIFICATE: 8, // 台胞证
  FOREIGN_PERMANENT_RESIDENT_CARD: 9, // 外国人永久居留身份证(绿卡)
  HONG_KONG_AND_MACAU_PASS: 10, // 港澳通行证
  TAIWAN_PASS: 22, // 台湾通行证
  HONG_KONG_AND_MACAU_AND_TAIWAN_PASS: 23, // 港澳台通行证
};

export const PASSPORT_TYPE_TEXT = {
  [PASSPORT_TYPE.IDENTITY_CARD]: "身份证",
  [PASSPORT_TYPE.PASSPORT]: "护照",
  [PASSPORT_TYPE.HONG_KONG_AND_MACAO_MAINLAND_PASS]: "回乡证",
  [PASSPORT_TYPE.TAIWAN_COMPATRIOT_CERTIFICATE]: "台胞证",
  [PASSPORT_TYPE.HONG_KONG_AND_MACAU_PASS]: "港澳通行证",
  [PASSPORT_TYPE.TAIWAN_PASS]: "台湾通行证",
  [PASSPORT_TYPE.HONG_KONG_AND_MACAU_AND_TAIWAN_PASS]: "港澳台通行证",
  [PASSPORT_TYPE.FOREIGN_PERMANENT_RESIDENT_CARD]: "外国人永久居留身份证(绿卡)",
};

export const PASSPORT_TYPE_OPTIONS = () => [
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.IDENTITY_CARD],
    value: PASSPORT_TYPE.IDENTITY_CARD,
  },
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.PASSPORT],
    value: PASSPORT_TYPE.PASSPORT,
  },
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.HONG_KONG_AND_MACAO_MAINLAND_PASS],
    value: PASSPORT_TYPE.HONG_KONG_AND_MACAO_MAINLAND_PASS,
  },
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.TAIWAN_COMPATRIOT_CERTIFICATE],
    value: PASSPORT_TYPE.TAIWAN_COMPATRIOT_CERTIFICATE,
  },
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.HONG_KONG_AND_MACAU_PASS],
    value: PASSPORT_TYPE.HONG_KONG_AND_MACAU_PASS,
  },
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.TAIWAN_PASS],
    value: PASSPORT_TYPE.TAIWAN_PASS,
  },
  {
    label:
      PASSPORT_TYPE_TEXT[PASSPORT_TYPE.HONG_KONG_AND_MACAU_AND_TAIWAN_PASS],
    value: PASSPORT_TYPE.HONG_KONG_AND_MACAU_AND_TAIWAN_PASS,
  },
  {
    label: PASSPORT_TYPE_TEXT[PASSPORT_TYPE.FOREIGN_PERMANENT_RESIDENT_CARD],
    value: PASSPORT_TYPE.FOREIGN_PERMANENT_RESIDENT_CARD,
  },
];

// 乘客类型
export const PASSENGER_TYPE = {
  ADULT_TICKET: 1, // 成人票
  CHILD_TICKET: 2, // 儿童票
};

export const PASSENGER_TYPE_TEXT = {
  [PASSENGER_TYPE.ADULT_TICKET]: "成人票",
  [PASSENGER_TYPE.CHILD_TICKET]: "儿童票",
};

// 出票是否成功
export const ORDER_RESULT_CODE = {
  SUCCESS: 200, // 出票成功
  SOLD_OUT: 1, // 已售完 （坐席无法满足）
  THERE_UNPAID_TICKETS: 2, // 存在未支付车票
  PASSENGER_INFO_ERROR: 3, // 乘客身份信息核验异常
  ITINERARY_CONFLICT: 4, // 行程冲突
  SUBMITTED_NAMES_INCONSISTENT: 5, // 提交姓名与票机默认不一致
  LIMIT_HIGH_CONSUMPTION: 6, // 限制高消费
  STOP_SELLING: 7, // 车次停运/维护/停售/无站点
  NETWORK_ERROR: 8, // 票机卡/网络故障等临时因素
  RESTRICTIONS_EPIDEMIC_AREAS: 9, // 疫情地区限制
  GUESTS_CLOSE: 10, // 客人要求取消
  OTHER: 11, // 其他
};

export const ORDER_RESULT_CODE_TEXT = {
  [ORDER_RESULT_CODE.SUCCESS]: "出票成功",
  [ORDER_RESULT_CODE.SOLD_OUT]: "坐席无法满足(已售完)",
  [ORDER_RESULT_CODE.THERE_UNPAID_TICKETS]: "存在未支付车票",
  [ORDER_RESULT_CODE.PASSENGER_INFO_ERROR]: "乘客身份信息核验异常",
  [ORDER_RESULT_CODE.ITINERARY_CONFLICT]: "行程冲突",
  [ORDER_RESULT_CODE.SUBMITTED_NAMES_INCONSISTENT]: "提交姓名与票机默认不一致",
  [ORDER_RESULT_CODE.LIMIT_HIGH_CONSUMPTION]: "限制高消费",
  [ORDER_RESULT_CODE.STOP_SELLING]: "车次停运/维护/停售/无站点",
  [ORDER_RESULT_CODE.NETWORK_ERROR]: "票机卡/网络故障等临时因素",
  [ORDER_RESULT_CODE.RESTRICTIONS_EPIDEMIC_AREAS]: "疫情地区限制",
  [ORDER_RESULT_CODE.GUESTS_CLOSE]: "客人要求取消",
  [ORDER_RESULT_CODE.OTHER]: "其他",
};

export const ORDER_RESULT_CODE_OPTIONS = () => [
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.SUCCESS],
    value: ORDER_RESULT_CODE.SUCCESS,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.SOLD_OUT],
    value: ORDER_RESULT_CODE.SOLD_OUT,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.THERE_UNPAID_TICKETS],
    value: ORDER_RESULT_CODE.THERE_UNPAID_TICKETS,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.PASSENGER_INFO_ERROR],
    value: ORDER_RESULT_CODE.PASSENGER_INFO_ERROR,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.ITINERARY_CONFLICT],
    value: ORDER_RESULT_CODE.ITINERARY_CONFLICT,
  },
  {
    label:
      ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.SUBMITTED_NAMES_INCONSISTENT],
    value: ORDER_RESULT_CODE.SUBMITTED_NAMES_INCONSISTENT,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.LIMIT_HIGH_CONSUMPTION],
    value: ORDER_RESULT_CODE.LIMIT_HIGH_CONSUMPTION,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.STOP_SELLING],
    value: ORDER_RESULT_CODE.STOP_SELLING,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.NETWORK_ERROR],
    value: ORDER_RESULT_CODE.NETWORK_ERROR,
  },
  {
    label:
      ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.RESTRICTIONS_EPIDEMIC_AREAS],
    value: ORDER_RESULT_CODE.RESTRICTIONS_EPIDEMIC_AREAS,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.GUESTS_CLOSE],
    value: ORDER_RESULT_CODE.GUESTS_CLOSE,
  },
  {
    label: ORDER_RESULT_CODE_TEXT[ORDER_RESULT_CODE.OTHER],
    value: ORDER_RESULT_CODE.OTHER,
  },
];

// 特殊要求
export const SPECIAL_REQUIREMENTS = {
  UNLIMITED: 0, // 无限制
  THERE_ARE_SPECIAL_REQUIREMENTS: 1, // 有特殊要求
  NO_SPECIAL_REQUIREMENTS: 2, // 无特殊要求
};

export const SPECIAL_REQUIREMENTS_TEXT = {
  [SPECIAL_REQUIREMENTS.UNLIMITED]: "无限制",
  [SPECIAL_REQUIREMENTS.THERE_ARE_SPECIAL_REQUIREMENTS]: "有特殊要求",
  [SPECIAL_REQUIREMENTS.NO_SPECIAL_REQUIREMENTS]: "无特殊要求",
};

export const SPECIAL_REQUIREMENTS_OPTIONS = () => [
  {
    label: SPECIAL_REQUIREMENTS_TEXT[SPECIAL_REQUIREMENTS.UNLIMITED],
    value: SPECIAL_REQUIREMENTS.UNLIMITED,
  },
  {
    label:
      SPECIAL_REQUIREMENTS_TEXT[
        SPECIAL_REQUIREMENTS.THERE_ARE_SPECIAL_REQUIREMENTS
      ],
    value: SPECIAL_REQUIREMENTS.THERE_ARE_SPECIAL_REQUIREMENTS,
  },
  {
    label:
      SPECIAL_REQUIREMENTS_TEXT[SPECIAL_REQUIREMENTS.NO_SPECIAL_REQUIREMENTS],
    value: SPECIAL_REQUIREMENTS.NO_SPECIAL_REQUIREMENTS,
  },
];

// 坐席
const seatNameStr = `硬座,软座,硬卧上,硬卧中,硬卧下,软卧上,软卧下,包厢硬卧,高级软卧上,高级软卧下,一等软座,二等软座,商务座,高级动卧上,高级动卧下,动卧上,动卧下,一等卧上,一等卧中,一等卧下,二等卧上,二等卧中,二等卧下,一等座,二等座,特等座,无座,特等软座,二等双软,一人软包,多功能座,一等双软,硬卧代硬座,软卧代软座,卧代二等座,卧代一等座`;
export const SEAT_OPTIONS = () =>
  seatNameStr.split(",").map((item) => ({ label: item, value: item }));
